theme: jekyll-theme-modernist
logo: https://github.com/fosslk/OpenDesign/blob/master/common/foss-text-logo.png?raw=true
title: FOSS Sri Lanka Campus Clubs
description: List of FOSS Sri Lanka Campus Clubs. Planning to start a club? Reach out to us.
url: https://cc-list.foss.lk
